### PR TITLE
refactor(generator): move schema fixes into patches directory

### PR DESCRIPTION
**Pull request by Duologic**
No-op, with #138 we'll have another set of patches that fixes a bunch of things around the openapi spec, this PR collects these fixes into an patches/ directory.

### CODE REVIEW

**Comment by Duologic** [comment]
rebased following #141

**Review by julienduchesne — COMMENTED** [review]
hmm, not sure I understand the adhesive concept. Is it like a patch?

**Comment by Duologic** [comment]
Alright, patches might be a better name, let me change that

**Comment by Duologic** [comment]
rebased.

**Review by julienduchesne — APPROVED** [review]

**Pull request merged**
