### PR TITLE
Fix: Update customAllValue parameter type to string in dashboard variable docs

### PR DESCRIPTION
**Pull request by isarns**
## Overview
This PR updates the documentation for dashboard variables to correct the `customAllValue` parameter's type. The parameter was previously documented as a boolean, but it is actually a string. This change aligns the documentation with the [Grafana documentation](https://grafana.com/docs/grafana/latest/dashboards/variables/#variable-best-practices) and the expected input type.

## Changes
- The `customAllValue` parameter type has been corrected from `bool` to `string` across the documentation where it is referenced.

## Impact
This change will help users by providing accurate information about the `customAllValue` parameter type, ensuring that dashboard variables are used effectively and as intended within Grafana dashboards.

Please review the changes and merge them if everything is in order.

### CODE REVIEW

**Comment by isarns** [comment]
> The documentation is generated from schemas in Grafana, so any error should be fixed there, or in Grafonnet veneers which overlay the generated code.

Can you point me to the right direction?

**Comment by isarns** [comment]
> The documentation is generated from schemas in Grafana, so any error should be fixed there, or in Grafonnet veneers which overlay the generated code.

I noticed that the Grafana schemas do not include the customAllValue parameter, so I made changes in the custom directory. Unfortunately, I am unable to run the `make generator` due to the following error:

```
+ jrsonnet -J vendor -S -c -m /Users/PATH/TO/grafonnet/gen/grafonnet-v10.2.0/docs/ --exec '(import '\''doc-util/main.libsonnet'\'').render(import '\''/Users/PATH/TO/grafonnet/gen/grafonnet-v10.2.0/main.libsonnet'\'')'
TRACE: render.libsonnet:18 warning: annotation both defined as object and package
no such field: any
                                                    : field <any> access
    vendor/doc-util/./render.libsonnet:106:15-39    : function <hasFields> call
    vendor/doc-util/./render.libsonnet:106:19-106:20: if condition
                                                    : evaluating argument
    vendor/doc-util/./render.libsonnet:93:8-93:9    : function <std.join> call
    vendor/doc-util/./render.libsonnet:89:22-38     : function <toString> call
+ finish
+ rm -rf /var/folders/6d/ck0zlsjx3vsd4x9r42y6knvr0000gn/T/tmp.TvPDPcrlFX
make: *** [gen/grafonnet-latest] Error 1
```

**Comment by Duologic** [comment]
I've made a PR back to align this PR with main: https://github.com/isarns/grafonnet/pull/1

**Comment by isarns** [comment]
@Duologic Thanks for that! 
Got it merged. 

How about the `make generator` issue I have encountered? I'm using an intel MAC, maybe it causes the issue?

**Comment by Duologic** [comment]
> no such field: any
I think you need to have a newer `jrsonnet` version.

**Comment by isarns** [comment]
> > no such field: any
> > I think you need to have a newer `jrsonnet` version.

I use this version 
`jrsonnet 0.4.2` which is the latest

**Comment by Duologic** [comment]
Probably need master, that version is old, bleeding edge here :innocent:

**Comment by Duologic** [comment]
The generate process should probably become containerized so we don't have these issues.

**Comment by isarns** [comment]
> Probably need master, that version is old, bleeding edge here 😇

Yep that worked thanks! 😃

**Comment by isarns** [comment]
@Duologic 

I will open a new PR without the other account that i pushed with accidentally.

**Comment by isarns** [comment]
Opened #189

**Pull request closed without merging**
